<?php

/**
 * Implementation of hook_form_alter().
 */
function uif_og_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'uif_import_form') {
    if ($form_state['storage']['step'] == 1) {
      list($types, $in) = og_get_sql_args();

      $res = db_query(db_rewrite_sql("SELECT n.nid, n.title, o.* FROM {node} n INNER JOIN {og} o ON n.nid = o.nid WHERE n.type $in AND n.status = 1 ORDER BY n.title"), $types);
      while ($group = db_fetch_object($res)) {
        $options[$group->nid] = t('Join %name.', array('%name' => $group->title));
      }
      
      // add our group select
      $form['og'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Default groups'),
        '#description' => t('All users in the CSV file will be added to these groups. If you want specific users to be added to additional groups, add a "groups" column like described in the "User import help" above.'),
        '#options' => $options,
      );

      // drop the 'Next' button down to the bottom
      $form['next']['#weight'] = 10;

      // stash our values on the 'storage' when doing a step submit
      $form['#submit'][] = '_uif_og_import_form_submit';
    }
  }
}

function _uif_og_import_form_submit($form, &$form_state) {
  // stash the groups in 'storage' for when we do a preview
  $form_state['storage']['og'] = $form_state['values']['og'];
}

/**
 * Implementation of hook_uif_help().
 */
function uif_og_uif_help() {
  $help  = '';
  $help .= '<p>' . t('Additional column for Organic Groups support:') . '</p>';
  $help .= '<ul><li>' . t('groups (optional) - a list of group nids or names seperated by commas. For multiple values, it <em>must</em> be enclosed in quotes, for example: "Group 1,Group 2"') . '</li></ul>';
  return array($help);
}

function _uif_og_parse_group_list($text) {
  return array_map('trim', explode(',', $text));
}

/**
 * Implementation of hook_uif_validate_all_users().
 */
function uif_og_uif_validate_all_users($user_list, $form_state) {
  // for performance reasons, we maintain a cache of whether a group is valid or not 
  $group_cache = array();

  $errors = array();
  foreach ($user_list as $user_data) {
    if (!empty($user_data['groups'])) {
      foreach (_uif_og_parse_group_list($user_data['groups']) as $group) {
        $valid = FALSE;

        if (isset($group_cache[$group])) {
          $valid = $group_cache[$group];
        }
        else {
          // super light weight way to verify that a group exists and is valid
          $node = NULL;
          if (is_numeric($group)) {
            $node = db_fetch_object(db_query("SELECT nid, type FROM {node} WHERE nid = %d", $group));
          }
          else {
            $node = db_fetch_object(db_query("SELECT nid, type FROM {node} WHERE title = '%s' LIMIT 1", $group));
          }
          if ($node && og_is_group_type($node->type)) {
            $valid = TRUE;
          }
          $group_cache[$group] = $valid;
        }

        if (!$valid) {
          $invalid_groups[$group] = TRUE;
          if (is_numeric($group)) {
            $errors[] = t('Unable to find group with id %nid', array('%nid' => $group));
          }
          else {
            $errors[] = t('Unable to find group with title %title', array('%title' => $group));
          }
        }
      }
    }
  }

  return $errors;
}

/**
 * Implementation of hook_uif_user_post_create().
 */
function uif_og_uif_post_create($account, $user_data, $form_state) {
  // grab the default groups from the form
  $groups = empty($form_state['storage']['og']) ? $form_state['values']['og'] : $form_state['storage']['og'];
  $groups = array_keys(array_filter($groups));

  // take the groups for this individual user
  if (!empty($user_data['groups'])) {
    foreach (_uif_og_parse_group_list($user_data['groups']) as $group) {
      if (!is_numeric($group)) {
        $group = db_fetch_object(db_query("SELECT nid FROM {node} WHERE title = '%s' LIMIT 1", $group))->nid;
      }
      if ($group && !in_array($group, $groups)) {
        $groups[] = $group;
      }
    }
  }

  foreach ($groups as $gid) {
    og_subscribe_user($gid, $account);
  }
}

/**
 * Implementation of hook_uif_user_post_update().
 */
function uif_og_uif_post_update($account, $user_data, $form_state) {
  uif_og_uif_post_create($account, $user_data, $form_state);
}

